version: '3.9'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
        PGPORT: 5432
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: exchangemonitor
    ports:
      - "5432:5432"
